name: Build Android APK

on:
  push:
    branches: [ "main", "master", "رئيسي" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Find and Build Gradle Project
        run: |
          GRADLE_DIR=$(find . -name "gradlew" -exec dirname {} \;)
          if [ -n "$GRADLE_DIR" ]; then
            cd "$GRADLE_DIR"
            chmod +x gradlew
            ./gradlew assembleRelease
          else
            GRADLE_BUILD=$(find . -name "build.gradle*" -exec dirname {} \; | head -n 1)
            cd "$GRADLE_BUILD"
            gradle assembleRelease
          fi

      - uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: '**/build/outputs/apk/release/*.apk'
